[2023-04-18 16:04:38,133] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.15.25:5002 (Press CTRL+C to quit) - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:04:38,135] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:04:40,913] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:04:40] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:04:40,940] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:04:40] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:04:41,029] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:04:41] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:04:41,030] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:04:41] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:04:41,030] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:04:41] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:04:41,203] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:04:41] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:04:46,897] WARNING del_previsao() L136  Erro ao deletar previsao #'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L136 
[2023-04-18 16:04:46,904] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:04:46] "[33mDELETE /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:04:55,511] WARNING get_produto() L105  Erro ao buscar previsao 'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L105 
[2023-04-18 16:04:55,512] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:04:55] "[33mGET /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:05:04,931] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:05:04] "POST /previsao HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:05:12,594] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:05:12] "GET /previsoes HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:05:44,445] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:05:44] "[33mGET /produtos HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:05:55,487] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:05:55] "[33mPOST /produto HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:05:58,937] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:05:58] "[33mOPTIONS /produto?nome=maresias HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:08,424] INFO _log() L224   * Detected change in 'C:\\Users\\leticia.gerola\\Desktop\\Pessoal\\pos_grad\\mvp_sprint_1\\back_end\\model\\previsao.py', reloading - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:08,557] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:10,825] INFO _log() L224   * Detected change in 'C:\\Users\\leticia.gerola\\Desktop\\Pessoal\\pos_grad\\mvp_sprint_1\\back_end\\app.py', reloading - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:10,956] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:28,109] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.15.25:5002 (Press CTRL+C to quit) - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:28,111] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:29,830] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:06:29] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:29,844] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:06:29] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:29,919] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:06:29] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:29,921] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:06:29] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:29,922] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:06:29] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:30,064] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:06:30] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:06:33,949] WARNING del_previsao() L135  Erro ao deletar previsao #'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L135 
[2023-04-18 16:06:33,954] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:06:33] "[33mDELETE /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:07:32,794] WARNING get_produto() L104  Erro ao buscar previsao 'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L104 
[2023-04-18 16:07:32,796] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:07:32] "[33mGET /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:07:42,269] WARNING get_produto() L104  Erro ao buscar previsao 'maresias', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L104 
[2023-04-18 16:07:42,271] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:07:42] "[33mGET /previsao?nome_praia=maresias HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:07:48,640] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:07:48] "[33mGET /produtos HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:07:52,378] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:07:52] "[33mPOST /produto HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-18 16:07:55,521] WARNING get_produto() L104  Erro ao buscar previsao 'maresias', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L104 
[2023-04-18 16:07:55,522] INFO _log() L224  127.0.0.1 - - [18/Apr/2023 16:07:55] "[33mGET /previsao?nome_praia=maresias HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
