[2023-04-05 15:35:23,730] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.15.25:5002 (Press CTRL+C to quit) - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:25,295] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:25] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:25,306] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:25] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:25,425] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:25] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:25,427] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:25] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:25,430] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:25] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:30,059] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:30] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:30,085] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:30] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:30,094] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:30] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:30,095] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:30] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:30,296] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:30] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:34,660] WARNING del_previsao() L137  Erro ao deletar previsao #'Teste', Previsao não encontrada na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L137 
[2023-04-05 15:35:34,662] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:34] "[33mDELETE /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-05 15:35:43,999] WARNING get_produto() L106  Erro ao buscar previsao 'Teste', Previsao não encontrado na base :/ - call_trace=C:\Users\leticia.gerola\Desktop\Pessoal\pos_grad\mvp_sprint_1\back_end\app.py L106 
[2023-04-05 15:35:44,001] INFO _log() L224  127.0.0.1 - - [05/Apr/2023 15:35:44] "[33mGET /previsao?nome_praia=Teste HTTP/1.1[0m" 404 - - call_trace=C:\Users\leticia.gerola\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
